/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

import fs from 'fs';

export default {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  oldBylaws: [{type: 'autogenerated', dirName: 'old-bylaws'}],
  constitution: [{type: 'autogenerated', dirName: 'constitution'}],
  oldConstitution: [{type: 'autogenerated', dirName: 'old-constitution'}],
  termsOfReference: [{type: 'autogenerated', dirName: 'terms-of-reference'}],
  // all: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
